name: life_advice
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  mvc_pattern: any
  provider: ^6.0.4
  internet_connection_checker: any
  overlay_support: any
  connectivity_plus: any
  persistent_bottom_nav_bar_v2: ^4.2.6
  google_fonts: 2.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: any
  font_awesome_flutter: ^10.3.0

flutter_icons:
  android: true
  ios: true
  image_path: "asset/images/app_logo.png"
  min_sdk_android: 20

flutter_native_splash:
  color: "#ffffff"
  image: asset/images/app_logo.png
  branding: asset/images/app_logo.png
  color_dark: "#121212"
  image_dark: asset/images/app_logo_dark.png
  branding_dark: asset/images/app_logo_dark.png

  android_12:
    image: asset/images/app_logo.png
    icon_background_color: "#ffffff"
    image_dark: asset/images/app_logo_dark.png
    icon_background_color_dark: "#121212"

  web: false

flutter:

  uses-material-design: true

  assets:
    - asset/images/
  #   - images/a_dot_ham.jpeg

